"""Add user name to comments

Revision ID: a0d7ea709e10
Revises: 62b1476e1fff
Create Date: 2021-02-28 10:10:02.807697

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a0d7ea709e10"
down_revision = "62b1476e1fff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_name", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_column("user_name")

    # ### end Alembic commands ###
